image: alpine:3.15.4

pages:
  stage: deploy
  script:
    - apk add --no-cache python3 jekyll
    - scripts/deploy.sh
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  only:
    - main
